### ISSUE TITLE
Status of this repository?

### ISSUE THREAD

**Issue by anjmao** [golang/appengine#116]
Hi, can somebody give status about this repo? Is it maintained?

**Comment by mvdan** [comment]
What makes you think it isn't? The last commit is from just over a month ago. It is normal for activity to fall off a bit around the holidays.

**Comment by xStrom** [comment]
@anjmao yeah it's maintained but as low priority. App Engine has been the red-headed stepchild ever since Compute Engine got announced.

If you want something fixed, then your best strategy is to diagnose/fix it yourself and hope that someone will take interest in that fix. Mere high level reports won't penetrate anyone's todo lists.

**Comment by anjmao** [comment]
@mvdan Sorry, I just investigating if I can use standart environment, but as I registered an issue https://github.com/golang/appengine/issues/114 that it is not possible to deploy app from my own GOPATH if I'm using vendoring and I didn't got any response about this issue status after two weeks, but this issue seems like important one.

@xStrom Thanks, your answer helps a lot.
