### ISSUE TITLE
datastore.RunInTransaction requires x/net/context.Context 

### ISSUE THREAD

**Issue by venantius** [golang/appengine#132]
(This is on Go 1.8)

At the moment `datastore.RunInTransaction` takes a function with a `golang.org/x/net/context.Context` argument rather than a `context.Context` argument. 

While most of the appengine package seems happy to take a `context.Context` in place of an `x/net/context.Context` (for instance, `datastore.NewKey`), for some reason the fact that this gets passed as a function literal causes the compiler to barf, which in turn means we have to link against `golang/x/net/context.Context` instead. 

I think migrating the appengine package to `context.Context` is probably on the roadmap at this point anyways, but I wanted this behavior for posterity because it caught me off guard.

**Comment by mtraver** [comment]
In general I agree, it would be nice to use the standard lib `context` everywhere. However it's not a trivial change because we still support Go 1.6 on App Engine; `golang.org/x/net/context.Context` wasn't moved into the standard library until 1.7.

The good news is that in Go 1.9 `golang.org/x/net/context.Context` is an alias for `context.Context` so the problem goes away, and Go 1.9 is now supported on App Engine (in beta since last month, see https://groups.google.com/forum/#!topic/google-appengine-go/MFTqqCSl-po).

This is a good read on the subject: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/312

**Comment by astec** [comment]
@venantius Make sure you've installed the latest version of SDK that contains the Go 1.9.

I'm not sure about `goapp test` but `goapp serve` definitely should change to specified Go version in `app.yaml`. 

https://cloud.google.com/appengine/docs/standard/go/config/appref
```
runtime: go
api_version: go1.9
```
Above works for me with Go Standard SDK version: 1.9.64 - 2018-03-28

**Comment by venantius** [comment]
Ah, fantastic. I had `app.yml` rather than `app.yaml` - once I renamed it my configuration was picked up fine and everything's grand. Cheers.
