### ISSUE TITLE
let's encrypt autocert

### ISSUE THREAD

**Issue by vendelin8** [golang/appengine#148]
Hi,

I know that gcloud has SSL support, but it doesn't cover wildcard subdomains like *.example.com. I'm working on a gcloud project that has to have subdomains like this, and I'd like to add autocert feature with let's encrypt. I found this example:
https://stackoverflow.com/questions/37321760/how-to-set-up-lets-encrypt-for-a-go-server-application
And a couple of others, but I'd need to add the listener of the cert manager to the http ListenAndServe method in all the examples I found. I can't do that with appengine, because it creates http listeners out of box.

Please let me know, how could I fix this issue. Thanks!

**Comment by sbuss** [comment]
Like you mention, I don't think you can add this due to the way App Engine handles and automatically sets up `http.ListenAndServe`.

I love Let's Encrypt, but there's an even easier solution: https://cloud.google.com/appengine/docs/standard/python/securing-custom-domains-with-ssl -- let Google generate and manage your cert for you, or upload your Let's Encrypt generated cert to us. I recommend the former, since it's super easy and will handle pretty much everything for you.

**Comment by vendelin8** [comment]
Yep. Pretty much everything, but that doesn't cover wildcard subdomains. And I really need that.

Would it be possible for the appengine to config http Handler object somehow?

**Comment by vendelin8** [comment]
Is it at least considered, or should I try other things?
