### ISSUE TITLE
Put everything in this repository so we have a option to have a single goroot

### ISSUE THREAD

**Issue by gertcuykens** [golang/appengine#23]
I understand why you did this sdk double goroot magic workaround, but just give us a choice to specify and separate all appengine code from the real goroot please even if it does the exact same thing but made appengine compatible. Every IDE would be thankful and also everybody that needs to dig deep in performance issues and figure out if its the compiler or the standard library that can be improved is going to be thankful as well. Just adding all modified goroot packages is all I ask, it will not break anything. Or just make a separate branch that includes it, then it doesn't even change the master repository.

related to https://code.google.com/p/googleappengine/issues/detail?id=13268

**Comment by okdave** [comment]
There is only one goroot when you're running on App Engine: the one that comes with the SDK. We provide a full Go toolchain (which includes the goroot) so that (1) the environment is close to the one you'll have when running on the server and (2) developers don't need to download Go separately if they only use App Engine.

This repo contains all the necessary packages you need to access any of the APIs on App Engine. There's really nothing left in the goroot that we can move here.

Let me know if there's anything else I can clarify.
