### ISSUE TITLE
unable to import both major versions of appengine at the same time due to internal protos

### ISSUE THREAD

**Issue by codyoss** [golang/appengine#311]
Please see issue for more context: https://github.com/googleapis/google-cloud-go/issues/7760

Although theses deps should likely be updated it should not break users if they have both imported at the same time. The internal protos should have a new namespace for the v2 library to make the global protobuf registry happy.

**Comment by codyoss** [comment]
The issue: https://github.com/golang/appengine/blob/f9c3e90be8b414958cf81ca4524af726919267f7/internal/remote_api/remote_api.proto#L4

**Comment by xStrom** [comment]
See also #281 & #228.

**Comment by xStrom** [comment]
I agree that it should be fixed. I'm stuck using old versions of unrelated libraries because of this issue.

**Comment by jinglundong** [comment]
> having both import should not cause panics.

Yes, it's a fair behavior that we should support. We will reserve some time in our next sprint to at least working on a proposal.

**Comment by jinglundong** [comment]
After reading some of the related issues (https://github.com/googleapis/google-cloud-go/issues/7760, https://github.com/golang/appengine/issues/281 and https://github.com/golang/appengine/issues/228), it appears that migrating from github.com/golang/protobuf to google.golang.org/protobuf is the short-term solution. 

One common challenge of this type of issues is that Google internal code base and OSS repos may diverge. We might be lucky here because this Github repo is the source of truth if I recall correctly. I can (or ask someone in our team) to give this change a shot.

**Comment by trakhimenok** [comment]
@jinglundong any estimates for resolution?

**Comment by jinglundong** [comment]
Sorry for being irresponsive on this issue. I will provide an estimate next week.

**Comment by jinglundong** [comment]
This issue aligns with an internal goal of our team. The current ETA is June 30th 2023.

**Comment by xStrom** [comment]
Unfortunate of course, however I would like to thank you for keeping us informed. Very rare trait for a googler!
