### ISSUE TITLE
datastore.Query.GetAll does not support slices created by reflection

### ISSUE THREAD

**Issue by wolfgangmeyers** [golang/appengine#37]
When writing local tests, I found that passing in a slice that has been created by reflection results in a "datastore: invalid entity type" error being returned. If I pass in an identical slice that was not created by reflection, the operation works as expected. This problem is simple to reproduce:

```
import (
	"github.com/stretchr/testify/suite"
	"google.golang.org/appengine/aetest"
	"google.golang.org/appengine/datastore"
	"reflect"
	"testing"
)

type Object struct {
	Name string
}

type SliceReflectionTestSuite struct {
	suite.Suite
}

// This test fails
func (suite *SliceReflectionTestSuite) TestWithReflection() {
	ctx, done, err := aetest.NewContext()
	if err != nil {
		suite.T().Fatal(err)
	}
	defer done()

	sliceType := reflect.TypeOf([]*Object{})
	result := reflect.MakeSlice(sliceType, 0, 0).Interface()
	query := datastore.NewQuery("User")
	_, err = query.GetAll(ctx, &result)
	suite.Nil(err) // fails
}

// This test doesn't fail
func (suite *SliceReflectionTestSuite) TestWithNoReflection() {
	ctx, done, err := aetest.NewContext()
	if err != nil {
		suite.T().Fatal(err)
	}
	defer done()

	result := make([]*Object, 0, 0)
	query := datastore.NewQuery("User")
	_, err = query.GetAll(ctx, &result)
	suite.Nil(err) // passes
}

// This test shows that the reflection-created slice is equal to the manually created slice
func (suite *SliceReflectionTestSuite) TestSliceEquality() {
	sliceType := reflect.TypeOf([]*Object{})
	reflectionSlice := reflect.MakeSlice(sliceType, 0, 0).Interface()
	nonReflectionSlice := []*Object{}
	suite.Equal(nonReflectionSlice, reflectionSlice)
}

func TestSliceReflectionTestSuite(t *testing.T) {
	suite.Run(t, new(SliceReflectionTestSuite))
}
```

**Comment by adams-sarah** [comment]
The key point you are missing is in `TestSliceEquality`.
We pass pointers to `query.GetAll`, not the values themselves.

So if you change your test to:

```go
func (suite *SliceReflectionTestSuite) TestSliceEquality() {
	// ...
	suite.Equal(&nonReflectionSlice, &reflectionSlice)
}
```

you will see in the test output:

```
--- FAIL: TestSliceEquality (0.00s)
        Error Trace:    your_test.go:54
	Error:		Not equal: 
			expected: &[]*appengine_test.Object{}
			received: (*interface {})(0xc420107870)
```

The solution (on your end) is to type-assert your interface{} before taking its address, eg:

```go
result := reflect.MakeSlice(sliceType, 0, 0).Interface().([]*Object)
```

Sorry :(. I realize it is unlikely that you'd be able to do this.

<br>

I agree, it would be great if we could support *interface{} arguments to query.SetAll. But the solution would likely be a combination of some complex reflection and some additional complex control flow because of the difference between:

```go
var v1 interface{} = []*Object{}
var v2 = []*Object{}

reflect.ValueOf(&v1).Elem().Type() // interface{}
reflect.ValueOf(&v2).Elem().Type() // []*Object
```

and because we do allow some interface types, eg. `PropertyLoadSaver`, whose interface type information would be lost if we did something like:

```go
vv := reflect.ValueOf(&v1).Elem()
vv = reflect.ValueOf(vv.Interface())
vv.Type() // []*Object
```

Is this functionality critical to your application?

**Comment by wolfgangmeyers** [comment]
Actually, I found a workaround, which was to pass through a concrete slice to the datastore. So no, this is not critical. Thanks for the detailed explanation!

Something worth noting though, is that I can create structs with reflect.New(..).Interface(), which is accepted by the datastore when fetching by key.
