### ISSUE TITLE
appengine.NewContext panics on flex

### ISSUE THREAD

**Issue by broady** [golang/appengine#76]
via https://github.com/GoogleCloudPlatform/golang-samples/issues/264

Probably caused by https://github.com/golang/appengine/pull/68?

/cc @zombiezen

**Comment by zombiezen** [comment]
Took a look and that panic is a different one.  #68 makes it panic if an App Engine API is called on a context derived from `context.Background`.  The panic you are seeing is what happens if you attempt to obtain a `Context` for an `http.Request` that didn't originate from App Engine.  Is there some middleware that is altering the request that the handler receives?

**Comment by broady** [comment]
yes, via `appengine.Main()`. An hour ago, I thought this was a regression, but after thinking more, it's always been like this.

**Comment by zombiezen** [comment]
Right. `appengine.NewContext` doesn't work in the slightest on Flex; it only worked on Managed VMs.  This is working as intended, but does seem to have a high foot-gun factor.
